import type { StrategyEducation } from "../../src/lib/education"

const docs = ["https://developers.uniswap.org/docs/get-started/concepts/liquidity-providers/concentrated-liquidity", "https://uniswap.org/whitepaper-v3.pdf", "https://hyperliquid.gitbook.io/hyperliquid-docs/onboarding/how-to-start-trading", "https://hyperliquid.gitbook.io/hyperliquid-docs/trading/margining", "https://hyperliquid.gitbook.io/hyperliquid-docs/trading/funding"]
const education: StrategyEducation = {
  family: "Hedging", goal: "hedge", complexity: "Advanced", management: "Active management",
  returnSource: "Earn swap fees from an active ETH/USDC liquidity range while a short ETH perpetual offsets its current directional exposure. Net income depends on fees exceeding funding, trading, gas and rebalancing costs; neither fees nor funding are guaranteed.",
  exposure: "Hold an ETH/USDC Uniswap V3 LP on Ethereum plus a separate USDC-margined ETH short on HyperCore. The LP's ETH quantity changes as price moves. Target near-zero net ETH delta by adjusting the short, including any ETH fees; this reduces first-order price exposure, not volatility itself or all losses.",
  tradeOff: "LPs buy into declines and sell into rallies. Their changing delta requires active hedging: divergence loss, adverse selection and rebalancing costs remain. Separate margin can liquidate during a rally even while the LP gains elsewhere.",
  fitsIf: ["You want trading-fee income with less directional ETH exposure during uncertain or orderly downtrending markets.", "You understand LP ranges and perpetuals, can actively rebalance, and reserve separate USDC margin and gas."],
  reconsiderIf: ["Price exits the range, net delta breaches your written tolerance, or fees no longer cover costs.", "Margin or withdrawal liquidity deteriorates, funding exceeds budget, or you cannot monitor both legs."],
  example: {
    title: "A neutral entry can drift as the LP changes",
    starting: "At ETH = 3,000 USD, deposit 1 ETH + 3,000 USDC into a 2,000–4,500 USD range and reserve another 3,000 USDC as isolated short margin. Total capital: 9,000 USD.",
    action: "Short 1 ETH at 3,000 USD to offset the initial LP delta. These three scenarios deliberately leave the short unchanged to illustrate why a live hedge must be rebalanced.",
    assumptions: "Illustrative Uniswap V3 inventory with L = 1 / (1/√3,000 − 1/√4,500). Short P&L = 3,000 − ending ETH price. USDC = 1 USD; aligned spot/perp prices; no liquidation. Assume collected fees converted to USDC of 80 USD in the moving-price scenarios or 100 USD when flat, and 30 USD aggregate funding/execution/gas costs in each. These amounts are invented examples, not rates. Rebalanced returns depend on the price path and every hedge trade; these are not dynamically neutral backtests.",
    benchmark: "Hold the same initial 1 ETH + 6,000 USDC without LP or short; include all reserved capital.",
    scenarios: [
      {label: "Orderly decline", condition: "ETH reaches 2,000 USD, the lower boundary. The LP becomes about 2.224745 ETH; the unchanged short gains 1,000 USD.", assets: "LP ≈ 2.224745 ETH; short margin equity 4,000 USDC; net collected fees less costs 50 USDC.", value: "Total ≈ 8,499.49 USD versus unhedged holding 8,000 USD.", next: "Net ETH delta has drifted to about +1.224745 ETH. Reassess or close the range and adjust the short; below this boundary active fees stop."},
      {label: "Unexpected rally", condition: "ETH reaches 4,500 USD, the upper boundary. The LP becomes about 6,674.23 USDC; the short loses 1,500 USD.", assets: "LP ≈ 6,674.23 USDC; margin equity 1,500 USDC; net collected fees less costs 50 USDC.", value: "Total ≈ 8,224.23 USD versus unhedged holding 10,500 USD.", next: "The LP now has zero ETH while the old short leaves −1 ETH delta. Reduce-only close or resize the short; LP assets elsewhere do not replenish margin."},
      {label: "Price ends unchanged", condition: "ETH ends at 3,000 USD. The LP inventory and short P&L end unchanged in this fixed-hedge example.", assets: "LP 1 ETH + 3,000 USDC; margin 3,000 USDC; net fees less costs 70 USDC.", value: "Total 9,070 USD versus unhedged holding 9,000 USD.", next: "Illustrative fees exceed costs here. A continuously rebalanced hedge can still lose on a choppy path returning to the same price; check actual costs."},
    ],
  },
  monitor: ["Recalculate net ETH delta = current LP ETH + unconverted ETH fees − short ETH quantity. Set a written tolerance and review after meaningful price moves or position changes.", "Track fee income net of funding, gas, slippage and hedge-trading costs; monitor range boundaries and whether liquidity remains active.", "Check isolated margin, mark price, liquidation threshold and platform/bridge alerts. Keep collateral independent from LP funds."],
  exit: "Plan both legs together: remove liquidity and collect fees, then promptly resize or reduce-only close the short to match remaining ETH exposure. Check actual fills and residual exposure before withdrawing margin. Sequential execution leaves temporary directional risk.",
  implementations: [{key: "uniswap-hyperliquid-eth", label: "ETH/USDC V3 LP + ETH short · Uniswap / Hyperliquid", protocol: "uniswap", product: "Uniswap V3 ETH/USDC range plus isolated ETH perpetual short on Hyperliquid", network: "ethereum", assets: ["ETH", "USDC"], requirements: ["ETH/WETH and USDC for an active Ethereum LP range; ETH for gas. Verify the official pool, token addresses, fee tier and liquidity before entry.", "Separate USDC collateral for the Hyperliquid ETH short; this plan uses the documented Arbitrum deposit route with ETH there for gas. Verify current eligibility and contract availability.", "Record range, delta tolerance, funding budget, margin buffer and exit rules. Matrix's Hedging Calculator is in development and is not ready; use an independently verified calculation before opening either leg."], enter: "Add the selected LP range and read its actual ETH inventory. Deposit separate USDC, explicitly choose isolated margin, then short the current LP ETH delta. Check fills, margin and net exposure. Recalculate after each LP or hedge change.", accounting: "The short hedges current ETH delta, not the full dollar value of the LP. As ETH falls the LP normally holds more ETH; as it rises it holds less. Include unconverted ETH fees and any other intended exposure. Delta-neutral is a changing target, not a guaranteed fixed state.", exit: "Coordinate LP withdrawal/fee collection with reduce-only hedge adjustment or closure. Verify remaining token quantities and zero unwanted short exposure before withdrawing free collateral.", risks: "Changing delta, divergence loss, adverse selection, funding, rebalancing costs, liquidation, basis, execution gaps, contract/bridge/platform failure and USDC depeg.", sources: docs, reviewedAt: "2026-10-08"}],
  foundations: ["liquidity", "divergence", "borrowing"], tools: ["hedging", "impermanent-loss"],
}
export const hedgeStrategy = {
  legacyId: "STRATEGY_018", slug: "delta-neutral-lp-hedge", name: "Delta-Neutral LP",
  summary: "Earn LP swap fees while actively hedging changing ETH exposure in uncertain or downtrending markets.",
  description: "Pair an ETH/USDC liquidity range with a short ETH perpetual sized to the LP's current delta. Target less directional exposure while collecting trading fees, and rebalance as the token mix changes. This advanced plan does not eliminate volatility losses, funding costs or liquidation risk.",
  objectives: ["yield", "hedging", "advanced"], assets: ["ETH", "USDC"], protocols: ["uniswap", "hyperliquid"], networks: ["ethereum", "arbitrum", "hyperliquid"],
  steps: [
    {title: "Prepare", description: "Choose a liquid ETH/USDC range, reserve independent USDC margin, and write delta, cost and margin limits. The Hedging Calculator is in development; verify sizing independently."},
    {title: "Enter the LP", description: "Verify official pool and token addresses, supply the chosen range and record actual ETH inventory. Fee income requires active liquidity and trades."},
    {title: "Hedge current delta", description: "Use separate USDC on Hyperliquid, choose isolated margin and short the LP's current ETH quantity. Verify fills and residual delta; do not short the LP's total dollar value."},
    {title: "Monitor and rebalance", description: "Recalculate inventory and ETH fees as prices move. Adjust the hedge within your tolerance and track all costs against fees; rebalancing has its own execution risk."},
    {title: "Reconsider", description: "Exit or resize at range boundaries, breached margin limits or negative net economics. A violent sell-off can overwhelm monitoring and liquidity."},
    {title: "Exit both legs", description: "Withdraw LP and fees, promptly resize or reduce-only close the short, verify remaining ETH exposure and then withdraw free margin. Manage temporary execution gaps."},
  ],
  riskText: "Delta hedging reduces directional exposure but cannot eliminate LP volatility/divergence losses. Costs, funding, liquidation and failures on either platform can outweigh fees.", education,
}
