import type { MarketFit } from "../../src/lib/types"

export const EDITORIAL_VERSION = "market-context-v2"
// Editorial context, not a safety rating, return forecast or entry signal.
export const marketContexts: Record<string, MarketFit> = {
  STRATEGY_011: { regimes:["BULL","SIDEWAYS","BEAR"], secondaryRegimes:["LATE_BULL_DISTRIBUTION","LOW_VOL_COMPRESSION","HIGH_VOLATILITY_CHOP","CAPITULATION_DELEVERAGING"], explanation:"A cash-oriented position for taking risk off late in a bull cycle, waiting through ranges, or preserving optionality in a bear market. Borrower demand sets the rate, not the market label. During capitulation, depeg and withdrawal-liquidity risks need extra scrutiny; this is not an automatic safe haven." },
  STRATEGY_004: { regimes:["BULL","SIDEWAYS"], secondaryRegimes:["EARLY_RECOVERY","ALT_EXPANSION","LOW_VOL_COMPRESSION","BTC_LED_EXPANSION"], explanation:"For an existing ETH holder who wants borrower interest while retaining ETH exposure during recovery, expansion or a quiet range. BTC-led expansion does not make ETH a BTC proxy: this can fit only if you already intend to keep ETH despite relative weakness. Bear protection is not its objective; a small increase in token units can be overwhelmed by price losses." },
  STRATEGY_007: { regimes:["BULL","SIDEWAYS"], secondaryRegimes:["EARLY_RECOVERY","ALT_EXPANSION","LOW_VOL_COMPRESSION"], explanation:"Most relevant when you intend to keep ETH or SOL through recovery, broader crypto expansion or a quiet consolidation. Network rewards are separate from price gains. Staking still operates in a bear market, but is not surfaced as a defensive bear strategy because it retains asset downside and may introduce exit delays or token discounts." },
  STRATEGY_016: { regimes:["SIDEWAYS"], secondaryRegimes:["LOW_VOL_COMPRESSION"], explanation:"The default fee-income range is best considered in a bounded, relatively quiet market where trades can occur inside the chosen range. Low volatility can also mean fewer fees. Breakouts and high-volatility reversals can make the position one-sided or inactive; do not treat trading volume alone as a reason to use a narrow range." },
  STRATEGY_001: { regimes:["BEAR","SIDEWAYS"], secondaryRegimes:["CAPITULATION_DELEVERAGING"], explanation:"Designed for bear and sideways markets when you deliberately want ETH exposure at lower prices. The capitulation/deleveraging phase is relevant only if you have already chosen to buy ETH through a sharp decline and can hold through a large further drop; a fast move can fill the range within minutes. This is not a bottom detector or a claim that capitulation is a favourable entry. Use the plan only when the full range is below spot at entry; entering in-range during a recovery sells ETH as price rises, and recovery through an open range can reverse accumulated ETH. Deploy only an amount you would be comfortable holding through that further decline. Fees are incidental and small relative to price moves." },
  STRATEGY_009: { regimes:["BULL","SIDEWAYS"], secondaryRegimes:["ALT_EXPANSION","LATE_BULL_DISTRIBUTION","HIGH_VOLATILITY_CHOP"], explanation:"A planned selling range for a rally, late-cycle distribution or repeated upward swings. The objective is converting an existing holding to stablecoins, not maximising LP fee income. In a falling bear market the selling range may never execute, so this is not a stop-loss or downside hedge." },
  STRATEGY_022: { regimes:["BULL","SIDEWAYS"], secondaryRegimes:["EARLY_RECOVERY","ALT_EXPANSION","LOW_VOL_COMPRESSION"], explanation:"For someone willing to retain both ETH and BTC exposures through recovery, broad participation or a stable relative-price range. Relative price behaviour matters more than the dollar-market label: strong ETH/BTC divergence can underperform holding both. BTC-led expansion is deliberately excluded because one-sided leadership weakens the default two-asset thesis." },
  STRATEGY_018: { regimes:["SIDEWAYS","BEAR"], secondaryRegimes:["HIGH_VOLATILITY_CHOP","CAPITULATION_DELEVERAGING"], explanation:"An actively hedged LP for uncertain, sideways or downtrending conditions where meaningful trading fees may offset costs. Adjust the short as LP ETH inventory changes; this limits directional exposure, not volatility/divergence losses. Violent chop increases rebalancing costs, and capitulation is a stress case requiring executable liquidity and ample independent margin, not an automatic entry signal. Pause or exit if fees cannot cover costs, the range becomes inactive or either leg cannot be monitored." },
}
